---
name: Auto-sync Lock Files on PR
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'package-lock.json'
      - 'ios/Podfile.lock'
      - 'package.json'
      - 'ios/Podfile'

env:
  NODE_VERSION: 20.13.1

jobs:
  sync-lock-files-to-base:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-base-branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ci/configure-git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: ci/download-pr-lock-files
        run: |
          PR_SHA="${{ github.event.pull_request.head.sha }}"
          
          echo "Downloading lock files from PR SHA: $PR_SHA"
          
          # Скачиваем package-lock.json из PR
          if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3.raw" \
                  -o package-lock.json \
                  "https://api.github.com/repos/${{ github.repository }}/contents/package-lock.json?ref=$PR_SHA" 2>/dev/null; then
            echo "Downloaded package-lock.json"
          else
            echo "ℹpackage-lock.json not changed in PR"
          fi
          
          # Скачиваем Podfile.lock из PR
          if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3.raw" \
                  -o ios/Podfile.lock \
                  "https://api.github.com/repos/${{ github.repository }}/contents/ios/Podfile.lock?ref=$PR_SHA" 2>/dev/null; then
            echo "Downloaded ios/Podfile.lock"
          else
            echo "ℹios/Podfile.lock not changed in PR"
          fi

      - name: ci/commit-lock-files
        run: |
          # Проверяем есть ли изменения
          if git diff --quiet package-lock.json ios/Podfile.lock; then
            echo "No changes in lock files, skipping commit"
            exit 0
          fi
          
          # Коммитим только если есть изменения
          git add package-lock.json ios/Podfile.lock
          git commit -m "sync: update lock files from PR #${{ github.event.pull_request.number }}

Auto-sync lock files to prevent merge conflicts:
- package-lock.json
- ios/Podfile.lock

From PR: ${{ github.event.pull_request.title }}
Author: ${{ github.event.pull_request.user.login }}"
          
          git push origin ${{ github.event.pull_request.base.ref }}
          
          echo "✅ Lock files synced to ${{ github.event.pull_request.base.ref }}"

      - name: ci/comment-success
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔄 **Lock Files Synced**
              
Lock files have been automatically synced from this PR to \`${{ github.event.pull_request.base.ref }}\` to prevent merge conflicts.

**Files updated:**
- \`package-lock.json\`
- \`ios/Podfile.lock\`

You can now merge this PR without conflicts! 🚀`
            });