name: PR Build (APK)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build devDebug APK
        run: ./gradlew --no-daemon :app:assembleDevDebug

      - name: Collect APK path
        id: collect
        shell: bash
        run: |
          APK_PATH=$(ls -1 app/build/outputs/apk/dev/debug/*.apk | head -n 1)
          echo "apk-path=$APK_PATH" >> "$GITHUB_OUTPUT"
          echo "Found APK: $APK_PATH"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: maxtv-app-dev-debug-${{ github.run_number }}
          path: ${{ steps.collect.outputs.apk-path }}
          if-no-files-found: error
          retention-days: 7

      - name: Comment with artifact link
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const artifactName = `maxtv-app-dev-debug-${{ github.run_number }}`;
            const runUrl = `${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            const body = [
              '✅ Сборка APK выполнена.',
              '',
              `- Артефакт: ${artifactName}`,
              `- Скачать: ${runUrl}#artifacts`
            ].join('\n');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });


