---
name: Sync Package JSON from PR
on:
    pull_request:
        types:
            - labeled
        paths:
            - 'package.json'
            - 'package-lock.json'

env:
    NODE_VERSION: 20.13.1

jobs:
    sync-package-json:
        runs-on: ubuntu-22.04
        if: ${{ contains(github.event.label.name, 'Sync Package') }}

        steps:
            - name: ci/checkout-main
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  ref: main
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: ci/setup-node
              uses: actions/setup-node@a57c6165b6296b7582531f72318bb9966f708e20 # v4.1.0
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: ci/configure-git
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: ci/fetch-pr-files
              run: |
                  PR_NUMBER="${{ github.event.pull_request.number }}"
                  PR_HEAD_SHA="${{ github.event.pull_request.head.sha }}"

                  echo "Fetching files from PR #$PR_NUMBER (SHA: $PR_HEAD_SHA)"

                  # Скачиваем package.json из PR
                  curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Accept: application/vnd.github.v3.raw" \
                       -o package.json.tmp \
                       "https://api.github.com/repos/${{ github.repository }}/contents/package.json?ref=$PR_HEAD_SHA"

                  # Проверяем, что файл валидный JSON
                  if node -e "JSON.parse(require('fs').readFileSync('package.json.tmp', 'utf8'))"; then
                    mv package.json.tmp package.json
                    echo "package.json successfully downloaded and validated"
                  else
                    echo "Downloaded package.json is not valid JSON"
                    exit 1
                  fi

                  # Опционально скачиваем package-lock.json если он изменился в PR
                  if curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3.raw" \
                          -o package-lock.json.tmp \
                          "https://api.github.com/repos/${{ github.repository }}/contents/package-lock.json?ref=$PR_HEAD_SHA"; then
                    mv package-lock.json.tmp package-lock.json
                    echo "✅ package-lock.json also updated"
                  fi

            - name: ci/install-dependencies
              run: |
                  echo "Installing dependencies to verify package.json..."
                  npm ci --legacy-peer-deps

            - name: ci/commit-changes
              run: |
                  PR_NUMBER="${{ github.event.pull_request.number }}"

                  if git diff --quiet package.json package-lock.json; then
                    echo "No changes detected"
                    exit 0
                  fi

                  git add package.json package-lock.json
                  git commit -m "sync: update package.json from PR #$PR_NUMBER

                  - Synchronized package.json with PR #$PR_NUMBER
                  - Dependencies verified and package-lock.json updated

                  Co-authored-by: ${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.id }}+${{ github.event.pull_request.user.login }}@users.noreply.github.com>"

                  git push origin main

            - name: ci/comment-on-pr
              uses: actions/github-script@v7
              with:
                  script: |
                      await github.rest.issues.createComment({
                        issue_number: ${{ github.event.pull_request.number }},
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `🔄 **Package Sync Completed**
                        
                        The \`package.json\` and \`package-lock.json\` files have been synchronized from this PR to the main branch.
                        
                        **Changes:**
                        - package.json updated
                        - Dependencies verified
                        - package-lock.json regenerated
                        
                        **Workflow Run:** [View Details](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID})`
                      });
